### ISSUE TITLE
视频下载

### ISSUE THREAD

**Issue by dadanshang** [LussacZheng/video-downloader-deploy#11]
大神能把aria2加上去吗？

**Comment by LussacZheng** [comment]
请先阅读之前的相关讨论：#6 
和 已存在的文档：[Wiki - Work with aria2](https://github.com/LussacZheng/video-downloader-deploy/wiki/Aria2)

**Comment by LussacZheng** [comment]
鉴于此 Issue 重复，且 72h 内没有收到任何回复，我将关闭此 Issue 。如有需要仍可以在此继续讨论。
