### ISSUE TITLE
请问西瓜视频、今日头条的视频如何下载，you-get youtube-dl annie也无法解析下载

### ISSUE THREAD

**Issue by lyjhyjyes** [LussacZheng/video-downloader-deploy#12]
用IDM下载，只能下载出来音频+视频分开的2个文件，好崩溃

**Comment by LussacZheng** [comment]
> 请问西瓜视频、今日头条的视频如何下载，you-get youtube-dl annie也无法解析下载

如果 you-get, youtube-dl, annie 都无法解析下载，那就需要 换用别的工具 或 等待官方更新 ，但那就不在本项目的讨论范围之内了。

> 用IDM下载，只能下载出来音频+视频分开的2个文件

使用 FFmpeg 可以合并音频和视频，你可以去搜索一下如何使用，或找一个简单易用的 FFmpeg GUI ，如小丸工具箱等。

**Comment by lyjhyjyes** [comment]
谢谢，小丸工具箱一直有下，但不知道它用了FFmpeg

Lussac <notifications@github.com> 于2020年8月20日周四 下午9:11写道：
