### ISSUE TITLE
请问视频下载器能实现you-get youtube-dl annie完整功能吗

### ISSUE THREAD

**Issue by lyjhyjyes** [LussacZheng/video-downloader-deploy#15]
您好，已经下载了，能使用。请问视频下载器能实现you-get youtube-dl annie完整功能吗，没有阉割

**Comment by LussacZheng** [comment]
能，此脚本只是一键部署，完全相当于通过官方途径安装的 you-get/youtube-dl/annie。

---

**如果不是遇到 Bug ，请不要再为了这种一句话的问题而新开 Issue ，还烦请直接在这个 Issue 下继续讨论。**

此外，希望你花一点时间阅读一下 [Wiki - Complete Usage Guide / 完全使用指南](https://github.com/LussacZheng/video-downloader-deploy/wiki/UsageGuide) ，尽管文档目前尚不完整。

**Comment by drw2005** [comment]
更新youtube-dl特别慢，其他两个都非常快。
youtube-dl-2020.09.  60%[===========>        ]   1.83M  3.27KB/s    eta 5m 14s

**Comment by LussacZheng** [comment]
> 更新youtube-dl特别慢，其他两个都非常快。
> youtube-dl-2020.09. 60%[===========> ] 1.83M 3.27KB/s eta 5m 14s

网络问题。请尝试通过 `Deploy.bat -> [6]高级设置 -> [3]设置全局代理 -> N` 指定全局代理，或依照 [Wiki - FAQ](https://github.com/LussacZheng/video-downloader-deploy/wiki/FAQ#%E4%B8%8B%E8%BD%BD%E8%BF%87%E6%85%A2) 手动下载 `youtube-dl-*.tar.gz` 。
