### ISSUE TITLE
谢谢作者的付出，别名的批处理命令太方便了，别名proxy能添加修改代理端口号码？

### ISSUE THREAD

**Issue by mxzxck** [LussacZheng/video-downloader-deploy#16]
谢谢作者的付出，别名的批处理命令太方便了，别名proxy能添加修改代理端口号的功能码？现在国内墙的现状，翻墙经常会切换线路和端口。如果别名proxy能在当前窗口实时修改代理的端口，比如1080改为8100，那就更方便了。

**Comment by LussacZheng** [comment]
> 为别名 proxy 添加修改代理端口号的功能

现在你可以通过 `proxy use` 命令来为当前窗口指定代理（临时，关闭窗口后设置即丢失）。

完整的用法为 `proxy use <httpHost:port> <httpsHost:port>` ，例如：

```bat
>>> proxy use http://10.20.30.40:1234 https://50.60.70.80:5678

等效于：
set http_proxy=http://10.20.30.40:1234
set https_proxy=https://50.60.70.80:5678
```

简洁起见，你也可以只提供一个地址，甚至只提供一个端口号 `proxy use <[host:]port>` ，例如：


```bat
>>> proxy use http://10.20.30.40:1234

等效于：
set http_proxy=http://10.20.30.40:1234
set https_proxy=http://10.20.30.40:1234
```

```bat
>>> proxy use 1234

等效于：
set http_proxy=http://127.0.0.1:1234
set https_proxy=http://127.0.0.1:1234
```

你可以更新脚本文件，通过 `Deploy.bat` 重新导入默认别名 `proxy` ，再重新创建启动脚本并运行 `下载视频.bat` ，即可进行测试。

**Comment by mxzxck** [comment]
非常感谢，我马上就测试！
