### ISSUE TITLE
请问如何下载爱奇艺VIP视频？

### ISSUE THREAD

**Issue by Harley0726** [LussacZheng/video-downloader-deploy#17]
是否可以用cookie实现？

**Comment by LussacZheng** [comment]
可以通过 `-c`/`--cookies` 指定 cookies 文件。对于此脚本，cookies 文件放到 `Download\` 目录下即可。

```
you-get -c cookies.txt URL

annie -c cookies.txt URL

youtube-dl --cookies cookies.txt URL
```

据B站某位用户的测试反馈，爱奇艺与搜狐的 VIP 视频无法通过会员账号的 cookies 下载。
如果你已经有爱奇艺会员的话，也可以自行测试一下。

**Comment by Harley0726** [comment]
亲测B站可以。爱奇艺不行。
感谢！
