### ISSUE TITLE
无法更新

### ISSUE THREAD

**Issue by sinoshon** [LussacZheng/video-downloader-deploy#22]
网络一切正常，一直提示如下，烦请帮看看，Thanks♪(･ω･)ﾉ

====================================================
请输入选项的序号并按回车: 3

正在检查网络连接 (如果长时间无响应，请确认网络是否正常，或前往高级设置关闭"网络连接测试")...
无法访问 GitHub ，请检查网络连接。

**Comment by LussacZheng** [comment]
你能通过浏览器正常访问 [测试链接](https://raw.githubusercontent.com/LussacZheng/video-downloader-deploy/master/res/scripts/CurrentVersion) 吗？（目前应显示 `1.7.0-beta3` ）

- 不能：  
  你所使用的网络无法正常访问 GitHub ，请尝试更换网络环境（如使用移动热点）或在 `Deploy.bat` 的高级设置中配置全局代理。

- 能：  
  按下述步骤操作。

运行 `下载视频.bat` ，依次执行以下命令：

```batch
md _test & cd _test

set "_url=https://raw.githubusercontent.com/LussacZheng/video-downloader-deploy/master/res/scripts/CurrentVersion"

..\..\res\wget.exe --no-check-certificate %_url% -O NetTest.txt && echo 网络正常 || echo 网络异常
```

**将输出复制到此处。** 之后你可以自行删除 `Download\_test\` 文件夹。

**Comment by sinoshon** [comment]
我用的VPN是全局代理，能正常访问github网站。而且我在在 Deploy.bat 的高级设置中也配置了全局代理。

按照您上面的代码测试结果如下：

--2021-04-06 21:13:17--  https://raw.githubusercontent.com/LussacZheng/video-downloader-deploy/master/res/scripts/CurrentVersion
Connecting to 127.0.0.1:1080... failed: Bad file descriptor.
网络异常

Thanks♪(･ω･)ﾉ！

**Comment by LussacZheng** [comment]
请确认一下你的本地端口是不是 1080 。
