### ISSUE TITLE
初次部署脚本没反应

### ISSUE THREAD

**Issue by PDSCi996** [LussacZheng/video-downloader-deploy#23]
下载的最新脚本，可是初次部署时候点击“11”后显示“正在下载”后就没有了任何反应，已经有代理，从新进入高级选项，选择“选择下载地区”，显示当前下载地区为“cn”，点击“21”没有任何反应，不能切换国外源。
![初次部署](https://user-images.githubusercontent.com/50539888/131356657-5c7b377a-e334-42d9-92ca-fb196f5093f8.png)

**Comment by LussacZheng** [comment]
> 进入高级选项，选择“选择下载地区”，显示当前下载地区为“cn”，点击“21”没有任何反应，不能切换国外源。

其实是要在 "高级设置" 中直接输入 "21" ，而不是先输入 "2" ，再点击/输入 "21" 。类似于主菜单中 "[11/12/13]" 和 "[1]" 的关系。 "选择语言"一项也是如此。

没有统一操作逻辑确实是脚本的设计缺陷。

> 下载的最新脚本，可是初次部署时候点击“11”后显示“正在下载”后就没有了任何反应，已经有代理

请按下述步骤操作。

1. 在 "Deploy" 脚本所在目录，按住 <kbd>Shift</kbd>，同时单击鼠标右键，选择 "在此处打开PowerShell窗口" 或 "在此处打开CMD窗口" ，在弹出的窗口中输入并执行以下命令：

   ```batch
   echo --no-check-certificate > .\res\wget.opt
   ```

2. 确认 `res` 文件夹内有一个名为的 `wget.opt` 文件。

3. 重新打开 "Deploy" 脚本，并执行 "11" ，**将输出复制过来。** （选中文字后并点击右键即可复制）
   之后你可以自行删除 `res` 文件夹内的 `wget.opt` 文件。

4. 然后我才能知道问题具体出在哪。

**Comment by LussacZheng** [comment]
如果你嫌麻烦的话可以按主页说明，从 [蓝奏网盘](https://lussac.lanzoui.com/b05h5pfc) 下载 `video-downloader-deploy-2021xxxx[FULL+FFmpeg].zip` 。重新解压运行，应该不会出现任何问题。
