### ISSUE TITLE
高aria2过程的疑问

### ISSUE THREAD

**Issue by SONGjiemo** [LussacZheng/video-downloader-deploy#29]
![image](https://user-images.githubusercontent.com/46627639/156872420-8ecdee1e-51ce-49b6-a4c6-aa3ca33f95fa.png)
aria2.exe放到指定目录后，是不是就可以直接用多线程下载了。
我看到上图这一步，有疑问。是不是还需要配置他，如果是 我没有理解什么意思，因为图中有视频地址而地址是变化的。

期望答复我。

**Comment by LussacZheng** [comment]
文档里说的很清楚了：

> **只需提前将 aria2c.exe 加入环境变量** <sup>[\[1\]](https://github.com/LussacZheng/video-downloader-deploy/wiki/Aria2#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F)</sup> :
>
> 若你正在使用 video-downloader-deploy ，  
> 将 `aria2c.exe` 移动到 `usr\` 文件夹下，即与 `annie.exe` 或 `python-embed\` 同一级。打开 `下载视频.bat` ，输入以下命令检测是否配置正确：
> ```
> aria2c -v
> ```

简而言之，将 `aria2c.exe` 移动到 `usr\` 文件夹下即可。

> **youtube-dl 可以通过 `--external-downloader COMMAND` 和 `--external-downloader-args ARGS` 参数 <sup>[\[2\]](https://github.com/ytdl-org/youtube-dl#download-options)</sup> 来调用 aria2c** :
>
> ```
> --external-downloader COMMAND        Use the specified external downloader.
>                                      Currently supports aria2c,avconv,axel,c
>                                      url,ffmpeg,httpie,wget
> --external-downloader-args ARGS      Give these arguments to the external
>                                      downloader
> ```

- `--external-downloader` 参数用于指定下载器，这里我们用 `aria2c` ;
- `--external-downloader-args` 参数用于指定传递给 `aria2c` 的[参数](https://aria2.github.io/manual/en/html/aria2c.html), `-s 8` 指将同一份文件分成8份并行下载，也就是所谓的“多线程下载”。
  例子中的 `--external-downloader-args "-s 8"` 不是必须的，省略 `-s` 将默认为5线程 。为什么？因为官方文档是就么说的：[`Default: 5`](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-s) 。

---

总结，你要是搞不懂，就直接 `youtube-dl --external-downloader aria2c https://...视频网址...`

**Comment by SONGjiemo** [comment]
嗯嗯，理解了。
我最后问一下，aria2c.exe如何 加入环境变量呀。

**Comment by LussacZheng** [comment]
你要不再仔细看看我的回复？

**Comment by SONGjiemo** [comment]
刚刚测试 ，
直接卡了，不知道咋回事
![image](https://user-images.githubusercontent.com/46627639/156886506-eaf45317-522f-4c69-976c-fa134e3231e7.png)

**Comment by LussacZheng** [comment]
这个视频我能正常下载，你确认一下代理设置，或者换个非音乐(版权)类的短点的视频下载试一试，先看看能不能正常下载。

**Comment by SONGjiemo** [comment]
好的。

**Comment by SONGjiemo** [comment]
1、全局地址。显示计算机无法访问，设置禁用全局代理  就是卡死了。

你干脆把你的打包ZIP 发我吧。不测试了。

**Comment by LussacZheng** [comment]
1. 你的 aira2c 是在环境变量里的，没必要打包发你。
2. 卡住了就多等等。
3. 还有，没必要非得用 aria2c ，速度并快不了多少，youtube-dl 直接下就行。

**Comment by SONGjiemo** [comment]
1、aira2c 是在环境变量。这个如何配置我有点懵逼。
2、我是就复制到指定文件夹aira2文件
3、卡了，反正最后下载不了文件。然后就是 我发现 经过我一顿操作，然后什么都不能下载了。之前还可以直接下载m3u8的

要不，咱们加个QQ聊

**Comment by LussacZheng** [comment]
GitHub主页有我的邮箱

**Comment by SONGjiemo** [comment]
发了个邮箱。你打包发我试试
