### ISSUE TITLE
加入代理和ffmpeg启停选项

### ISSUE THREAD

**Issue by catshitz** [LussacZheng/video-downloader-deploy#3]
1. 下载YouTube视频时，可加入代理以配合shadowsocks等扶墙工具方便下载，如
`set HTTP_PROXY=http://127.0.0.1:1080`
`set HTTPS_PROXY=http://127.0.0.1:1080`
2. ffmpeg合并少数视频时会出问题，可于deploy加入卸载选项方便临时停用。

**Comment by LussacZheng** [comment]
感谢您的想法与建议！

### 关于 代理设置
- 由于代理端口可变，而且 you-get, youtube-dl, annie 各下载器的代理参数选项 ( `--proxy` ` -x` `-s` 等) 不尽相同，不宜硬编码预先写进脚本里。
- 个人认为如果需要另行手动设置端口，那便与每次下载视频时直接加上参数相差无几。
- 因此我觉得只需要在 `下载视频.bat` 中 加入例子/提示 ，每次下载时直接照例引用、复制粘贴即可。

### 关于 FFmpeg
- 由此脚本配置的 FFmpeg 保存在 `usr\ffmpeg\bin` 目录下，并由 `下载视频.bat` 添加临时环境变量以启用。因此能够通过 是否设置临时环境变量 来实现 FFmpeg 的 (启用/禁用) 切换。
- 此外，由于此脚本是以绿色便携版为目的，所以不宜永久修改环境变量。
- 正因如此，此脚本无法禁用/卸载 用户自行安装在别处的 FFmpeg 。

---

新特性已提交，现已支持**临时停用 FFmpeg** ，并添加了**代理参数选项**样例的提示。
请重新下载 master.zip ，解压覆盖原文件，并重新创建 `下载视频.bat` 以尝试。二者的设置均在 **选项[6]** 中，修改结果均体现在 `下载视频.bat` 中。

如果有任何问题或意见建议，希望您能继续深入讨论。

**Comment by LussacZheng** [comment]
另外我想了解一下，在什么情况下 FFmpeg 合并所下载的视频会产生问题？您能详细说一下相关细节或相关网站吗？

**Comment by catshitz** [comment]
> 并添加了**代理参数选项**样例的提示。

感谢采纳！加入代理主要因为初次deploy完整版时，annie源地址国内/本地下载速度过慢仅几KB/s，且个人主要下载youtube和外网视频，就想到在deploy.bat和下载视频.bat前手动加入ss等代理支持，为使脚本更加完善所以提出建议。

> 另外我想了解一下，在什么情况下 FFmpeg 合并所下载的视频会产生问题？您能详细说一下相关细节或相关网站吗？

非常抱歉，因在youtube下载的4k竖屏视频播放时部分画面为黑，起初以为是ffmpeg在合并时因编码格式有问题出错，后来发现是其他渲染器的问题，与ffmpeg无关，所以造成误会。
不过还是建议保持临时停用ffmpeg项，以防万一其自动合并的视频出错，可临时停用转为使用其他工具如mkvtoolnix等，当然绝大多数情况下用ffmpeg处理的视频都没有问题。

**Comment by LussacZheng** [comment]
国内通过 GitHub Releases 下载文件确实是个问题，
- 脚本中 you-get 是通过 [pypi.org](https://pypi.org/project/you-get/) 下载的，国内有镜像源（清华、阿里云等），所以能正常下载
- 而 youtube-dl *（仅 绿色配置 时）* 和 annie 都需要从 GitHub Releases 下载

一直也没有很好的办法解决这个问题。不过确实能通过给 wget 添加 -e 参数等方式使用代理，我可以在下次更新中添加这一设置。
```shell
wget -e https_proxy=http://127.0.0.1:1080 https://github.com/iawia002/annie/releases/download/0.9.5/annie_0.9.5_Windows_64-bit.zip
```

**Comment by LussacZheng** [comment]
新特性已提交，现已支持**为 Wget 设置参数 选项**。

请通过 `[6] 高级设置` -> `[4] 为 'wget' 设置参数选项` 查看细节。  
默认的代理参数样例可以在 `res\wget.opt` 中找到，使用文本编辑器打开文件，用 **#** 号注释掉默认的选项，并取消代理样例的注释即可。且应该通过再次执行 `选项[6]` -> `选项[4]` 以确认修改无误。

另需注意，脚本不会对 用户提供的参数的正确性 进行验证，所以需要用户自行判断是否应当修改。

**Comment by catshitz** [comment]
已更新，非常感谢！

**Comment by LussacZheng** [comment]
> 加入代理主要因为初次deploy完整配置时，annie源地址国内/本地下载速度过慢仅几KB/s，且本人主要下载youtube和外网视频，就想到在deploy.bat和下载视频.bat前手动加入ss等代理支持，为使脚本更加完善所以提出建议。

感谢您的建议！现已支持 **为 "Deploy.bat" 和 "下载视频.bat" 设置全局代理**。如果你还在使用此脚本的话，可以尝试下载更新。_若未在使用或不想更新，你无需阅读后文。_

---

注意事项：
1. 覆盖更新脚本文件后，请通过 `[6] 高级设置 -> [99] 为什么我无法切换以上的某项设置?` 来删除原配置文件 "deploy.settings"；  
   但这会导致所有的设置（ `[6]wget参数设置` 除外）恢复至默认，还请重新逐一修改，由此造成的不便深感抱歉。
2. 通过 `[6] 高级设置 -> [3] 设置全局代理` 来自定义代理地址和端口号。初次设置时请先输入 `T` 以启用默认的代理地址，之后重新运行脚本并回到这一步，输入 `N` 以自定义代理地址或端口号（一般 shadowsocks 默认端口号为1080，v2ray 默认端口号为10809）。
3. 修改后请重新执行 `[6] 高级设置 -> [3] 设置全局代理` 以确认设置无误。
4. 打开 "下载视频.bat" 并输入以下命令之一，即可进行测试：
   ```bash
   echo %http_proxy% & echo %https_proxy%

   # 或 

   ..\res\wget.exe -np https://www.youtube.com -O test.txt

   # 或

   youtube-dl https://www.youtube.com/watch?v=XXX
   ```
