### ISSUE TITLE
有个小建议

### ISSUE THREAD

**Issue by SONGjiemo** [LussacZheng/video-downloader-deploy#30]
1、希望可以设置这几个小工具某个为默认选择，当默认选择无法下载时候自动启用其他的去下载他。
选择了默认小工具后，可以直接黏贴  网址直接下载。不必每次加入 小工具名称。
2、使用小工具时候，经常放到后台去下载他。但是会卡了不继续下载 希望可以自动刷新 比如每分钟刷新一下。有时候还会直接下载失败
3、希望可以支持批量下载文件。

**Comment by LussacZheng** [comment]
1. 你可以为你的默认选择添加一个单字母的 [别名](https://github.com/LussacZheng/video-downloader-deploy#%E5%88%AB%E5%90%8D--alias) 以减短命令。
   ```
   # 设置 y="youtube-dl"，即可直接
   y https://...视频网址...
   ```

2. > - 当默认选择无法下载时候自动启用其他的去下载
    > - 卡了不继续下载 希望可以自动刷新

   本项目只提供命令行，不是GUI，更不是下载管理器。

3. you-get, youtube-dl, lux 都提供从文本文件中读取大量网址并下载。

   在 `Download` 目录下新建一个文本文件（名称任意，以 `123` 为例），将你要下载的视频网址每行一个粘贴到该文件中，然后执行：

   ```
   you-get -I 123.txt
   youtube-dl -a 123.txt
   lux -F 123.txt
   ```

**Comment by SONGjiemo** [comment]
> 1. 你可以为你的默认选择添加一个单字母的 [别名](https://github.com/LussacZheng/video-downloader-deploy#%E5%88%AB%E5%90%8D--alias) 以减短命令。
>    ```
>    # 设置 y="youtube-dl"，即可直接
>    y https://...视频网址...
>    ```
> 2. > * 当默认选择无法下载时候自动启用其他的去下载
>    > * 卡了不继续下载 希望可以自动刷新
>    
>    
>    本项目只提供命令行，不是GUI，更不是下载管理器。
> 3. you-get, youtube-dl, lux 都提供从文本文件中读取大量网址并下载。
>    在 `Download` 目录下新建一个文本文件（名称任意，以 `123` 为例），将你要下载的视频网址每行一个粘贴到该文件中，然后执行：
>    ```
>    you-get -I 123.txt
>    youtube-dl -a 123.txt
>    lux -F 123.txt
>    ```

明白了。

**Comment by SONGjiemo** [comment]
问一下，如果我加入yt-dlp.exe  这个时候，
批量下载格式是
you-get -I 123.txt
youtube-dl -a 123.txt
lux -F 123.txt

**Comment by LussacZheng** [comment]
为什么不能去看看官方文档呢？
`yt-dlp -a 123.txt`

**Comment by SONGjiemo** [comment]
> 

主要是，我柴鸡呀。哎

**Comment by SONGjiemo** [comment]
> 为什么不能去看看 [官方文档](https://github.com/yt-dlp/yt-dlp#filesystem-options) 呢？ `yt-dlp -a 123.txt`

![image](https://user-images.githubusercontent.com/46627639/159156272-6e440490-f433-48d7-9aa2-156d162a7308.png)
我看了文档后，可是设置并发数。我想问一下，使用你的命令行工具我如何修改默认的并发数呀。希望丢一个写好的文件我

**Comment by LussacZheng** [comment]
添加一个别名 (以并发数 5、别名 yd 为例)：
令 `yd = "yt-dlp -N 5"`，就可以用 `yd` 代替 `yt-dlp -N 5`

**Comment by SONGjiemo** [comment]
> 

在问个问题，以yt-dlp -a 123.txt为例子。5个线程数量。
那我能一个命令进行下载吗。

**Comment by SONGjiemo** [comment]
> 添加一个别名 (以并发数 5、别名 yd 为例)： 令 `yd = "yt-dlp -N 5"`，就可以用 `yd` 代替 `yt-dlp -N 5`

然后就是，我希望能指定换一个下载目录。在哪里修改呢

**Comment by SONGjiemo** [comment]
> 添加一个别名 (以并发数 5、别名 yd 为例)： 令 `yd = "yt-dlp -N 5"`，就可以用 `yd` 代替 `yt-dlp -N 5`

我尝试yt-dlp -N 5 -a 123.txt。可以下载，不知道是否成功了

**Comment by SONGjiemo** [comment]
刚刚看了，官方文档。是不是三个工具。要搞3个设置呀。有没有办法统一处理

**Comment by LussacZheng** [comment]
> 在问个问题，以yt-dlp -a 123.txt为例子。5个线程数量。 那我能一个命令进行下载吗。
> 我尝试yt-dlp -N 5 -a 123.txt。可以下载

没错，就是 `yt-dlp -N 5 -a 123.txt` 或 `yt-dlp -a 123.txt -N 5` 。

> 指定换一个下载目录

三个工具恰好都是用 `-o` 参数指定输出目录；  
其中 youtube-dl (及其衍生的 yt-dlp ) 的 `-o` 参数功能比较复杂，详见各自的项目文档。

> 是不是三个工具。要搞3个设置呀。

是的，各个下载工具定义的命令行参数各不相同。

> 有没有办法统一处理

像其他下载管理器，如果用户能统一处理的话，一定是开发者在背后程序逻辑中做了分别处理。
