### ISSUE TITLE
软件提供的三种下载方案包括我使用的其他软件如fdm下载你管视频只能跑70kb左右

### ISSUE THREAD

**Issue by PumpkinSin** [LussacZheng/video-downloader-deploy#31]
https://github.com/ytdl-org/youtube-dl/issues/29326
https://www.reddit.com/r/DataHoarder/comments/q2qsip/youtubedl_randomly_slow_speed_60kbs/
搜了下发现不只是我有这个问题，换youtubedl的分支https://github.com/yt-dlp/yt-dlp#readme可以跑满带宽……

**Comment by LussacZheng** [comment]
#24 是这样的。
