### ISSUE TITLE
YouTube 下载速度问题

### ISSUE THREAD

**Issue by LevineWoo** [LussacZheng/video-downloader-deploy#32]
代理直接打开网页看是秒开，20多万数据的，但用这个下载视频时就只有几十K，不知道是否我哪里设置错误呢？同一个代理。

**Comment by LussacZheng** [comment]
目前 you-get, youtube-dl, lux 下载 YouTube 的速度都有问题，[yt-dlp](https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe) 可以达到正常速度，你可以试试。[yt-dlp 的命令参数格式](https://github.com/yt-dlp/yt-dlp#usage-and-options) 与 youtube-dl 的基本相同。

https://github.com/LussacZheng/video-downloader-deploy/issues/24#issuecomment-1001020250

**Comment by ljyww83** [comment]
[WinError 10061] 由于目标计算机积极拒绝，无法连接。

**Comment by ljyww83** [comment]
[WinError 10061] 由于目标计算机积极拒绝，无法连接。
