### ISSUE TITLE
you-get 这个工具报错无法使用。希望提供指导方法

### ISSUE THREAD

**Issue by SONGjiemo** [LussacZheng/video-downloader-deploy#35]
![image](https://user-images.githubusercontent.com/46627639/199783028-4c6b0da0-67c2-40e9-a9a6-5abbcfdfa67e.png)
希望提供解决方法，或者希望能更新脚本。我相信其他人也遇到了这个问题

**Comment by LussacZheng** [comment]
1. 我这边能正常下载，请尝试更换网络环境。
2. you-get 是刻意设计成不显示具体报错信息的，你可以添加 `--debug` 参数来查看具体的错误信息，例如
   ```
   you-get --debug https://stallman.org/rms.jpg
   ```
   在不知道具体错误信息的情况下，我无法解决问题。

**Comment by SONGjiemo** [comment]
非常感谢、请教一下  yt-dlp  下载剧集的命令是什么。我找了一下发现都不对。发自我的 iPad在 2022年11月4日，10:18，Lussac ***@***.***> 写道：﻿

我这边能正常下载，请尝试更换网络环境。
you-get 是刻意设计成不显示具体报错信息的，你可以添加 --debug 参数来查看具体的错误信息，例如
you-get --debug https://stallman.org/rms.jpg

在不知道具体错误信息的情况下，我无法解决问题。

**Comment by SONGjiemo** [comment]
问一下yt-dlp下载剧集的命令。我搜索了发现别人给的命令直接报错。如果你知道 希望可以帮帮忙。谢谢🙏🏻️发自我的 iPad在 2022年11月4日，10:18，Lussac ***@***.***> 写道：﻿

我这边能正常下载，请尝试更换网络环境。
you-get 是刻意设计成不显示具体报错信息的，你可以添加 --debug 参数来查看具体的错误信息，例如
you-get --debug https://stallman.org/rms.jpg

在不知道具体错误信息的情况下，我无法解决问题。
