### ISSUE TITLE
有个需求，就是希望支持下载文件目录修改功能。

### ISSUE THREAD

**Issue by SONGjiemo** [LussacZheng/video-downloader-deploy#36]
背景：由于习惯文件放到了D盘软件盘，导致D盘非常容易攒满空间
1、我的需求非常简单，就是Deploy.bat里面有个选择下载目录选项，如默认下载到 D:\Download 或者E:\Download
2、如果没有时间，我希望能给个例子，也就是如何下载到指定目录。因为现在的命令就是 “软件名称+地址”  我希望有个指定下载目录的例子。

**Comment by LussacZheng** [comment]
- 为什么不试试用[搜索引擎](https://cn.bing.com/search?q=CMD%E5%88%87%E6%8D%A2%E7%9B%AE%E5%BD%95%E5%92%8C%E7%9B%98%E7%AC%A6)呢？
- 另外三个工具都提供了 `-o` 参数

请你不要再为了这种 搜索引擎能找到，或者文档中有明确说明的问题 而新建 Issue 了，如果非要问的话，请在进行过基本的搜索后，再在 [Discussions](https://github.com/LussacZheng/video-downloader-deploy/discussions/new) 中提问，并且请在同一个 Discussion 中问。
