### ISSUE TITLE
大佬您好！能否再将BBDown也集成进您的软件里呀！

### ISSUE THREAD

**Issue by asong2022** [LussacZheng/video-downloader-deploy#37]
大佬您好！能否再将BBDown也集成进您的软件里呀！下载B站高画质更方便一点[BBDown](https://github.com/nilaoda/BBDown/releases)
谢谢大佬！星星已点！

**Comment by asong2022** [comment]
已解决，将BBDown放入usr是不是就可以了？

**Comment by LussacZheng** [comment]
> 能否再将BBDown也集成进您的软件里

目前不会，在重写重构后有可能支持，但目前我没有动力或时间去推动相关重构计划。

> 将BBDown放入usr是不是就可以了？

可以，因为 `usr\` 等文件夹会被临时添加进环境变量，详见 https://github.com/LussacZheng/video-downloader-deploy/discussions/21#discussioncomment-319527 。
