### ISSUE TITLE
更新问题

### ISSUE THREAD

**Issue by AmberHan** [LussacZheng/video-downloader-deploy#38]
Lux You-get源项目有bug修复，脚本配置能否更新哈

**Comment by LussacZheng** [comment]
源项目没发行新版本号啊。如果你需要实时跟进bug修复，暂时只能

- 对于 you-get ，手动修改 `usr\you-get\src\you_get\` 下的源码
- 对于 lux
  -  自行编译
  -  从 lux 仓库的 [Actions](https://github.com/iawia002/lux/actions/workflows/builder.yml) 中获得编译好的可执行文件，例如下载[最近一次](https://github.com/iawia002/lux/actions/runs/4072637963)的 `lux-windows-amd64` (页面末尾)
