### ISSUE TITLE
启用全局代理以后，仍然不能下载youtube视频，用的clash

### ISSUE THREAD

**Issue by fanyuanhang** [LussacZheng/video-downloader-deploy#39]
启用全局代理以后，仍然不能下载youtube视频，用的clash

**Comment by LussacZheng** [comment]
找到本地端口后，在 `Deploy → 6高级设置 → 3设置全局代理 → N → 留空 → 输入本地端口 → 再输一遍本地端口` ，重新打开“下载视频”即可。

为了方便以后随时切换，先在 `Deploy → 6高级设置 → 3设置全局代理 → T` 将代理设为默认关闭，再通过 `Deploy → 7别名管理 → 2导入默认别名` ， 这样以后在“下载视频”中输入直接输入 `proxy` 就可以 启用/禁用 下载器走代理了。

注意：
- Clash的本地端口一般默认是`7890`。
- 启用代理时需要在 Clash 运行的情况下才能正常 (与 Clash 的 `System Proxy` 无关)；
- 禁用代理时与 Clash 的运行情况无关。
