### ISSUE TITLE
请教下能把aria2c多线程下载整合进去吗？

### ISSUE THREAD

**Issue by mxzxck** [LussacZheng/video-downloader-deploy#6]

**Comment by LussacZheng** [comment]
感谢您的建议，我会探索一下整合 aria2c 的可行性，如有任何进展都会在这里更新。

**Comment by LussacZheng** [comment]
我尝试了一下结合使用 三种工具 和 aria2c 。

### you-get

you-get 似乎不能调用外部下载器。理论上可以通过 `-u` 参数取得视频的真实地址，再通过 aria2 下载。但实际上我没能成功。

```shell
$ you-get -u https://www.bilibili.com/video/av59988590/
```

另见：GitHub soimort/you-get pull#1682 （为了避免出现在该 PR 下，不直接引用链接）

### youtube-dl <sup>[[1]](https://github.com/ytdl-org/youtube-dl#download-options)<sup>

youtube-dl 可以通过 `--external-downloader COMMAND` 和 `--external-downloader-args ARGS` 参数来调用 aria2c ，只需提前将 `aria2c.exe` 加入环境变量。例如：

   ```cmd
   $ youtube-dl --proxy http://127.0.0.1:10809 --external-downloader aria2c --external-downloader-args "-s 10" https://www.youtube.com/watch?v=0YF8vecQWYs

   :: or

   $ set "https_proxy=http://127.0.0.1:10809"
   $ youtube-dl --external-downloader aria2c --external-downloader-args "-s 8 --log=log.txt" https://www.youtube.com/watch?v=dQw4w9WgXcQ
   ```

### annie <sup>[[2]](https://github.com/iawia002/annie#aria2)<sup>

annie 则提供专门的 `-aria2` 参数来调用 aria2c ，但需要提前开启 aria2c RPC 。例如：
   ```shell
   $ annie -aria2 https://www.bilibili.com/video/av59988590/
   ```
   比起调用，用“委托”一词似乎更为准确，因为 annie 是解析出视频真实地址后移交给 aria2 下载，需要通过 aria2c RPC 进行通信。因此下载过程是完全根据 `aria2.conf` 或 aria2c 启动时的设置来运行的，比如视频保存的路径取决于 aria2 的设置而非 annie 的 `-o` 参数：
   ```shell
   # -o 参数无效
   $ annie -o D:/test -aria2 https://www.bilibili.com/video/av59988590/
   ```
   若要使用代理还需要提前指定 aria2 的 `--https-proxy` （详见 [官方文档](https://aria2.github.io/manual/en/html/aria2c.html#http-ftp-sftp-options) ）或在 WebUI 中修改 `HTTPS 代理服务器` 设置：
   ```cmd
   $ set "http_proxy=http://127.0.0.1:10809"
   $ annie -aria2 https://www.youtube.com/watch?v=TXpGWhdwXuo
   ```
   基于相同原因，下载分段视频后需要自行手动调用 FFmpeg 合并。

---

综上所述，三种工具配合 aria2c 使用的方式各不相同。如果三种工具都采用类似 youtube-dl 的调用模式，则可以很方便的将 aria2 整合进脚本（只需将 `aria2c.exe` 放入 `usr\` ）。但实际上让 annie 和 you-get 调用 aria2 完成下载较为繁琐，基本上相当于需要独立配置 aira2c/AriaNg 等。

**暂时没能想到很好的方法将其整合起来，如果你有好的想法请务必分享给我。**

另外如果需要 aira2 的配置方法 和 其配合 youtube-dl, annie 下载的步骤，我可以整理一下在 wiki 页面发布，简单叙述一下流程。

**Comment by LussacZheng** [comment]
配合使用 aria2 说明：[Wiki - Work with aria2](https://github.com/LussacZheng/video-downloader-deploy/wiki/Aria2)

**Comment by mxzxck** [comment]
我也测试了，发现整合aria2没有意义，我是通过XX-Net的8087端口翻墙的，youtube-dl下载youtube的速度已经是极限速度了，比Internet Download Manager的浏览器插件16线程下载youtube还快，youtube-dl调用aria2下载速度最慢，而且线程多了youtube会断开连接。谢谢你做的如此好用的脚本。简单实用。

**Comment by LussacZheng** [comment]
感谢你的分享。  

如果没有后续问题我会在 48 h 后关闭此 Issue。
