### ISSUE TITLE
繁體中文

### ISSUE THREAD

**Issue by Kaillis** [LussacZheng/video-downloader-deploy#7]
看到您的網站有人需要繁體中文，以下是我自己修改使用的版本，我只修改了文本部份，文檔的第一句不知道是不是這樣寫，如果有錯，麻煩你做合併的時候修改一下。

PS. 第一次使用 GitHub，不確定是不是這樣提交，如有錯請指教，謝謝。

`@rem - Encoding:big5; Mode:Batch; Language:zh-TW; LineEndings:CRLF -`
:: ========================= START OF TRANSLATION =========================
set "str_title=影片下載器 一鍵配置"
set "str_titleExpanded=========  %str_title%  ========"
:: ================= Menu Options
set "str_portable=免安裝配置"
set "str_quickstart=快速配置"
set "str_withpip=完整配置"
set "str_opt1=初始配置"
set "str_opt11=免安裝版，可以任意移動整體文件夾。默認"
set "str_opt12=快速體驗，適合臨時使用"
set "str_opt13=通過 pip 穩定更新，適合長期使用"
set "str_opt2=配置 FFmpeg"
set "str_opt3=更新所有影片下載器"
set "str_opt4=重新創建啟動腳本"
set "str_opt5=更新此腳本 (訪問 GitHub)"
set "str_opt6=高級設置"
set "str_please-choose=請輸入選項的序號並按Enter: "
set "str_please-choose-from=請從 11 , 12 , 13 中選擇。"
set "str_please-input-valid-num=請輸入有效的數字。"
set "str_please-set-DeployMode=未找到 "deploy.log" ，無法判斷配置模式，請手動選擇 [11, 12, 13]: "
set "str_please-perform-after-update= ^>^>^>建議更新後執行一次該選項^<^<^<"
:: ================= Notification
set "str_bat-is-latest=此腳本已是最新。"
set "str_bat-can-update-to=此腳本可更新至"
set "str_deploy-ok=配置已完成。"
set "str_upgrade-ok=更新已完成。"
set "str_is-latestVersion=已是最新發行版"
set "str_please-wait=請耐心等待下載完成"
set "str_please-init=請先執行初始配置。"
set "str_please-re-init=已進行過初始配置，請刪除 "usr" 文件夾後再執行此選項。"
set "str_please-check-connection=無法訪問 GitHub ，請檢查網絡連接。"
set "str_fileLost=文件丟失，請重新下載或解壓此腳本的所有文件。"
:: :: use ^) instead of ), since %str_open-webpage% will be used in "if ( ) esle( )"
set "str_open-webpage1=按任意鍵以查看 GitHub 主頁 (即打開瀏覽器訪問 GitHub^)"
set "str_open-webpage2=按任意鍵以獲取更新 (即打開瀏覽器訪問 GitHub^)"
set "str_exit=按任意鍵退出..."
:: ================= Procedure
set "str_downloading=正在下載"
set "str_unzipping=正在解壓"
set "str_upgrading=正在更新"
set "str_updating=正在更新"
set "str_checking-connection=正在檢查網絡連接 (如果長時間無響應，請確認網絡是否正常，或前往高級設置關閉"網絡連接測試")"
set "str_checking-update=正在檢查更新"
set "str_already-deploy=已配置。"
set "str_already-upgrade=已更新。"
set "str_already-exist=已存在。"
:: ================= Download Batch
:: ========= Download Batch - Guides
set "str_dl-guide1=下載影片的命令為："
set "str_dl-guide2=you-get/youtube-dl/annie + 影片網址"
set "str_dl-guide3=例如："
set "str_dl-guide4=默認下載最高清晰度。下載文件默認保存在 Download 目錄。"
set "str_dl-guide5=如果你想選擇清晰度、更改默認路徑，或想瞭解三種工具的其他用法，請百度或參考官方說明："
set "str_dl-guide6=如需更改以下設置，請根據對應序號前往 "Deploy.bat - 高級設置" 切換相關選項"
set "str_dl-guide7=下載 YouTube 等外網影片時請「為當前窗口啟用全局代理」或「添加額外代理參數」。"
set "str_dl-guide_wiki=中文說明"
:: ========= Download Batch - Contents
set "str_dl-bat=下載影片"
set "str_dl-bat-created=已創建啟動腳本 "%str_dl-bat%.bat" 。"
set "str_dl-bat-reset=檢測到腳本可能進行了更新，建議您執行一次 "Deploy.bat - [4]%str_opt4%" 。"
set "str_dl-bat-moved=未找到 "usr" 文件夾！請將此腳本移動到與 "Deploy.bat" 同一目錄，或通過其重新創建啟動腳本。"
:: ================= Advanced Settings
set "str_opt6-Expanded======= 高級設置 ======"
set "str_opt6_opt0=返回主菜單"
set "str_opt6_opt1=選擇語言 (Select Language)"
set "str_opt6_opt2=選擇下載地區"
set "str_opt6_opt3=設置全局代理"
set "str_opt6_opt4=(顯示/隱藏) 代理參數的命令示例"
set "str_opt6_opt5=(禁用/啟用) FFmpeg"
set "str_opt6_opt6=為 'wget' 設置參數"
set "str_opt6_opt7=指定系統位數"
set "str_opt6_opt8=(禁用/啟用) 更新時的網絡連接測試"
set "str_opt6_opt9=通過 ^(PyPI.org/GitHub_Releases^) 更新 you-get"
set "str_opt6_opt99=為什麼我無法切換以上的某項設置?"
:: ========= Advanced Settings - Common Notifications
set "str_enter-to-cancel=直接Enter以取消："
set "str_cancelled=輸入無效，已取消。"
set "str_please-confirm-changes=修改後請重新執行此選項以確認設置無誤。"
set "str_please-rerun=請重新運行此腳本以使設置生效。"
set "str_please-rerun-dlbat=請重新運行 "%str_dl-bat%.bat" 以使設置生效。"
:: ========= Advanced Settings - Option 1-2
set "str_please-select-language=[11] English ; [12] 繁體中文"
set "str_language-set-to=語言已設置為："
set "str_please-select-region=[21] 官方源 (origin) ; [22] 國內鏡像源 (cn)"
set "str_current-region=當前下載地區為："
set "str_region-set-to=下載地區已設置為："
:: ========= Advanced Settings - Option 3
set "str_globalProxy-enabled=全局代理：啟用"
set "str_globalProxy-disabled=全局代理：禁用 ^(默認^)"
set "str_current-globalProxy=若全局代理已啟用，則當前 CMD 窗口將使用的代理地址為："
:: :: used in "dl-bat"
set "str_current-globalProxy-cmd=當前 CMD 窗口所使用的代理地址為："
set "str_please-set-globalProxy_1=若需(禁用/啟用)全局代理，請輸入T；"
set "str_please-set-globalProxy_2=若需恢復至默認的代理地址，請輸入Y；"
set "str_please-set-globalProxy_3=若需自定義代理地址或端口號，請輸入N；"
set "str_please-set-proxyHost=請輸入 - 代理服務器地址^(留空則為 http://127.0.0.1 ^)："
set "str_please-set-httpPort=請輸入 - HTTP端口^(留空則為 1080 ^)："
set "str_please-set-httpsPort=請輸入 - HTTPS端口^(留空則為 1080 ^)："
set "str_reset-globalProxy-ok=代理地址已恢復至默認。"
set "str_set-globalProxy-ok=自定義代理地址已設置成功。"
:: ========= Advanced Settings - Option 4
set "str_proxyHint-enabled=代理參數的命令示例：顯示"
set "str_proxyHint-disabled=代理參數的命令示例：隱藏 ^(默認^)"
:: :: used in "dl-bat"
set "str_proxyHint-option=代理參數示例："
set "str_proxyHint_annie1=自 annie v0.9.8 起，其不再支持通過 -x 或 -s 參數設置代理。"
set "str_proxyHint_annie2=可通過環境變量 %%%%HTTP_PROXY%%%% 來設置代理，或啟用 [3]全局代理。"
:: ========= Advanced Settings - Option 5
set "str_ffmpeg-enabled=FFmpeg：啟用 ^(默認^)"
set "str_ffmpeg-disabled=FFmpeg：禁用"
:: ========= Advanced Settings - Option 6
set "str_current-wgetOpt=當前 'wget' 所使用的參數為："
set "str_please-edit-wgetOpt_1=請自行編輯 "res\wget.opt" 以修改默認參數。"
set "str_please-edit-wgetOpt_2=若需重新生成默認的 "wget.opt" ，請輸入Y；"
set "str_reset-wgetOpt-ok=已重新生成 "wget.opt" 。"
:: ========= Advanced Settings - Option 7
set "str_current-systemType=當前指定的系統位數為："
set "str_please-set-systemType=若需切換系統位數，請輸入T；"
set "str_systemType-set-to=系統位數已設置為："
:: ========= Advanced Settings - Option 8-9
set "str_netTest-enabled=更新時的網絡連接測試：啟用 ^(默認^)"
set "str_netTest-disabled=更新時的網絡連接測試：禁用"
set "str_upgradeOnlyViaGitHub-enabled=更新 you-get 的方式：通過 GitHub_Releases"
set "str_upgradeOnlyViaGitHub-disabled=更新 you-get 的方式：通過 PyPI.org ^(默認^)"
:: ========= Advanced Settings - Option 99
set "str_reset-settings_1=更新腳本後，若新增的設置無法切換，則需要刪除 "res\deploy.settings" 。"
set "str_reset-settings_2=但這會導致以上所有的設置([6]除外)恢復至默認。"
set "str_reset-settings_3=若確認刪除，請輸入Y；"
set "str_reset-settings-ok=已刪除 "res\deploy.settings" ，請嘗試重新更改設置。"
:: ========================= END OF TRANSLATION =========================
:: Select %_Region_% for sources.txt
set "_Region_=cn"

**Comment by LussacZheng** [comment]
**感谢你提供的翻译！** 我快速地浏览了一遍，大体上没有什么问题。

但是有几点细节需要向你确认：

## 用词选择

据我所知大陆与台湾的部分用词习惯有所不同，例如 "软件 -- 軟體"、"程序 -- 程式"、"网络 -- 網路" 等等。其他的一些转换我都非常赞同，例如例如你将 `res\scripts\lang_zh.bat` 中的 "视频下载器" 转换为了 "影片下載器" ：

https://github.com/LussacZheng/video-downloader-deploy/blob/fc3bbc12892f2c02b6e8c8705b853a1381874bd5/res/scripts/lang_zh.bat#L3

但我对台湾的用词习惯不怎么了解，有几点疑问希望和你探讨一下。

1. 将 "网络" 转换为 "網絡" 而没有选择 "網路"  
   https://github.com/LussacZheng/video-downloader-deploy/blob/fc3bbc12892f2c02b6e8c8705b853a1381874bd5/res/scripts/lang_zh.bat#L43

   ```cmd
   set "str_checking-connection=正在檢查網絡連接 (如果長時間無響應，請確認網絡是否正常，或前往高級設置關閉"網絡連接測試")"
   ```

2. 将 "服务器" 转换为 "服務器" 而没有选择 "伺服器"  
   https://github.com/LussacZheng/video-downloader-deploy/blob/fc3bbc12892f2c02b6e8c8705b853a1381874bd5/res/scripts/lang_zh.bat#L97

   ```cmd
   set "str_please-set-proxyHost=請輸入 - 代理服務器地址^(留空則為 http://127.0.0.1 ^)："
   ```

3. 书面用语应该选择 "了解" 还是 "瞭解" ？  
   https://github.com/LussacZheng/video-downloader-deploy/blob/fc3bbc12892f2c02b6e8c8705b853a1381874bd5/res/scripts/lang_zh.bat#L54

   ```cmd
   set "str_dl-guide5=如果你想選擇清晰度、更改默認路徑，或想瞭解三種工具的其他用法，請百度或參考官方說明："
   ```

希望你能帮助我简单辨析一下。

此外，台湾应该能直接访问 YouTube ，那么下面这句话是否需要隐藏或修改？例如改为 "下載愛奇藝等大陸影片網站時 ***"。

https://github.com/LussacZheng/video-downloader-deploy/blob/fc3bbc12892f2c02b6e8c8705b853a1381874bd5/res/scripts/lang_zh.bat#L56

**Comment by LussacZheng** [comment]
## 网络下载速度

为了适配台湾使用者的网络下载环境，需要选择合适的默认镜像源，希望你能帮助我进行几个下载速度测试。**当然如果你不想测试，可以忽略本条消息。**

按以下步骤操作即可：

1. （先关闭全局代理）运行 `下载视频.bat` 或 `Download_Video.bat` ，依次执行以下命令：

   ```cmd
   copy ..\res\wget.exe ..\usr\
   md _test & cd _test
   set "WgetOpt=-q --show-progress --progress=bar:force:noscroll --no-check-certificate"
   set "PypiCommon=packages/f2/7c/2e7193b4c601772b85e97ef95b1d45b01532084acd616c6c426526f94b72"
   ```

2. 不要关闭窗口，接下来需要你执行一些下载命令，来测试下载速度。每条下载命令都应被执行一次，麻烦你简单地比较一下 下载速度（下载所需时间也可）。如果你不嫌麻烦，每条下载命令可以执行 2~3 次，并粗略地比较平均下载速度。

3. 下载 Python

   ```cmd
   wget %WgetOpt% https://www.python.org/ftp/python/3.7.7/python-3.7.7-embed-win32.zip
   ```

   ```cmd
   wget %WgetOpt% https://mirrors.huaweicloud.com/python/3.7.7/python-3.7.7-embed-win32.zip
   ```

   ```cmd
   wget %WgetOpt% https://npm.taobao.org/mirrors/python/3.7.7/python-3.7.7-embed-win32.zip
   ```

4. 下载 PyPI

   ```cmd
   wget %WgetOpt% https://files.pythonhosted.org/%PypiCommon%/you-get-0.4.1432.tar.gz
   ```

   ```cmd
   wget %WgetOpt% https://mirrors.tuna.tsinghua.edu.cn/pypi/web/%PypiCommon%/you-get-0.4.1432.tar.gz
   ```

   ```cmd
   wget %WgetOpt% https://mirrors.huaweicloud.com/repository/pypi/%PypiCommon%/you-get-0.4.1432.tar.gz
   ```

5. 最后将结果反馈给我，例如：
  
   ```txt
   下载速度
   Python: 1 > 3 > 2
   PyPI: 3 > 1 > 2
   ```

   或

   ```txt
   下载时长
   Python: 2 > 3 > 1
   PyPI: 2 > 1 > 3
   ```

   或

   ```txt
   下载速度：都很快/很慢
   下载时长：相差不大
   ```

---

当然，如果有台湾本地的镜像站点，其提供 Python 和 PyPI 镜像的话，希望能告诉我。

**Comment by LussacZheng** [comment]
> 1. 網絡=香港，網路=台灣
> 2. 的確是應該改成“伺服器”，這個港台通用，是我疏忽了
> 3. 我上網翻查了一下資料，“瞭解”是台灣用的比較多，香港一般也是寫“了解”

既然是由你发起的，就依据香港的用词习惯。我会采用 "網絡" 、 "了解" 。

目前先将文件名设定为 `res\scripts\lang_cht.bat` (cht = Chinese Traditional)，如果以后需要分别维护，届时再改为两个文件：`res\scripts\lang_zh-HK.bat` 和 `res\scripts\lang_zh-TW.bat` 。

> 4. 是的，應該改成“下載愛奇藝等大陸影片網站時 ***”，另外還需要把文中代理一詞改為"VPN"，在港台我們都稱之為VPN

我想了解一下 Windows 系统中如何称呼 "代理" 。查看方法：按 `Win + R` 打开运行，输入 `inetcpl.cpl` 并 `Enter` 即可打开 ”網際網絡“ 设置。然后切换到 ”連線“ 选项卡，打开 “區域網絡設定” 。

- 在 “Win10 中文-简体” 系统中显示的是： `代理服务器` 、 `为 LAN 使用代理服务器` 、 `地址：` 、 `端口：` 。
  ![zh-CN](https://user-images.githubusercontent.com/23522476/78656594-371c9a80-78fa-11ea-9d8e-4a555bf409e7.png)
- 在我的 “Win7 中文-香港” 虚拟机中显示的是： `Proxy 伺服器` 、 `在您的區域網路使用 Proxy 伺服器` 、 `位址` 、 `連接埠` 。
  ![zh-HK](https://user-images.githubusercontent.com/23522476/78656611-3b48b800-78fa-11ea-940d-6cd6f7a58e9c.png)
- 在我的 “Win7 中文-台灣” 虚拟机中显示的是： `Proxy 伺服器` 、 `在您的區域網路使用 Proxy 伺服器` 、 `位址` 、 `連接埠` 。
  ![zh-TW](https://user-images.githubusercontent.com/23522476/78656805-819e1700-78fa-11ea-93ff-28c8fb2b0ae2.png)
- 在我的 “Win7 英语” 虚拟机中显示的是： `Proxy server` 、 `Use a proxy server for your LAN` 、 `Address` 、 `Port` 。

如果在你所使用的系统中，显示的也是 "Proxy 伺服器"，那么我倾向于使用 "Proxy" 来替换 "代理"。同时将 `地址` 、 `端口` 转换为  `位址` 、 `連接埠` 。你怎么认为？

---

> 下載速度：  
> Python: 1 > 2 > 3  
> PyPI: 1 > 3 > 2  
>
> 每個命令都執行了3次取平均值，最快的不用 1 秒下載完，最慢的也不過幾秒而已。

据此结果，港台优先使用官方源的下载链接 (代号 `origin` )更为合适。我会修改对应的代码。

```bat
:: Select %_Region_% for sources.txt
set "_Region_=origin"
```

**Comment by Kaillis** [comment]
> 如果在你所使用的系统中，显示的也是 "Proxy 伺服器"，那么我倾向于使用 "Proxy" 来替换 "代理"。同时将 `地址` 、 `端口` 转换为 `位址` 、 `連接埠` 。你怎么认为？
我的也是顯示 "Proxy 伺服器"，那就照你說的這樣更改

另外借地方詢問，我下載時想引用 Cookies 檔案應該放在哪裡？以 You-Get 為例：
`you-get -c cookies.sqlite`
我將 `cookies.sqlite` 放在 `video-downloader-deploy-master` 根目錄執行以上命令會顯示找不到檔案，請問要放在哪邊才是正確？因為下載國內的影片不少都要會員

**Comment by LussacZheng** [comment]
> 我下載時想引用 Cookies 檔案應該放在哪裡？以 You-Get 為例：
> `you-get -c cookies.sqlite`
> 我將 `cookies.sqlite` 放在 `video-downloader-deploy-master` 根目錄執行以上命令會顯示找不到檔案，請問要放在哪邊才是正確？因為下載國內的影片不少都要會員

- 将 `cookies.sqlite` 放在 `Download\` 目录下即可，因为 `下载视频.bat` 的工作目录为 `Download\` 。

- 或 仍将 `cookies.sqlite` 放在 `video-downloader-deploy` 根目录，并使用相对路径：

  ```cmd
  you-get -c ..\cookies.sqlite https://your.url/here
  ```

- 或 将 `cookies.sqlite` 放在任何位置，使用完整路径：

  ```cmd
  you-get -c "C:\Users\admin\Deskptop\cookies.sqlite“ https://your.url/here
  ```

如果路径中使用 `\` 不行就换成 `/` 。

*（将 `Download\` 设为工作目录是为了使视频文件默认下载到该目录下。）*

**Comment by LussacZheng** [comment]
我提交了一个新的代码分支 [`locale-cht`](https://github.com/LussacZheng/video-downloader-deploy/tree/locale-cht) ，我自己在虚拟机中测试没有问题。你可以点击 [这个链接](https://github.com/LussacZheng/video-downloader-deploy/archive/locale-cht.zip) 下载测试一下：

1. 将文件解压到一个新的目录下，以避免影响你现有的 `video-downloader-deploy-master` 。
2. （可选）从 `video-downloader-deploy-master\res\` 复制 `download` 文件夹及其里面的所有文件，到 `video-downloader-deploy-locale-cht\res\` 下。这一步可以节省下载时间。
3. 打开 `Deploy.bat` ，依次执行 `1` - `5` 每个选项（ `12` , `13` 不用执行）。
4. 输入 `6` 进入“高级设置”，除了不用执行 `[12] 簡體中文` ，随意测试几个选项。
5. 打开 `下載影片.bat` 。

如果以上过程中没有出现乱码字符，或其他问题，则说明一切正常。出现任何问题可以继续反馈给我。

无论测试结果如何，最后你都可以直接删除 `video-downloader-deploy-locale-cht\` 文件夹。

最终改进完毕后我会合并代码到主分支 `master` ，完成此 Issue 。

**Comment by Kaillis** [comment]
> * 将 `cookies.sqlite` 放在 `Download\` 目录下即可，因为 `下载视频.bat` 的工作目录为 `Download\` 。

原來是放在這裡，試了好幾個目錄都沒注意到工作目錄為`Download\` 

> 如果以上过程中没有出现乱码字符，或其他问题，则说明一切正常。出现任何问题可以继续反馈给我。

測試正常，沒有發現亂碼
