### ISSUE TITLE
作者你好！代理能否增加支持socks5协议。

### ISSUE THREAD

**Issue by mxzxck** [LussacZheng/video-downloader-deploy#9]
目前中国大陆翻墙稳定的比如trojan和v2ray默认都是socks5协议，请问方便添加代理支持socks5协议，目前默认只有http和https协议，可默认支持http协议的翻墙工具很容易被阻断。谢谢

**Comment by LussacZheng** [comment]
其实你只要在 `Deploy.bat -> [6]高级设置 -> [3]设置全局代理 -> [N]自定义代理地址` 指定 **代理服务器地址** 时输入 `socks5://127.0.0.1` 而非 `http://127.0.0.1` 即可。

例如使用 V2Ray 时可以这样设置：
```
若需自定义代理地址或端口号，请输入N；
直接回车以取消：n

请输入 - 代理服务器地址(留空则为 http://127.0.0.1 )：socks5://127.0.0.1
请输入 - HTTP端口(留空则为 1080 )：10808
请输入 - HTTPS端口(留空则为 1080 )：10808
自定义代理地址已设置成功。
```

**Comment by mxzxck** [comment]
谢谢指教！还有个新问题 Youtube-dl   配合aria2 多线程我目前遇到个怪情况，比如下载整个youtube频道，aria2 多线程只对第一个视频下载生效，后面第二个的视频开始aria2调用就失效了。
比如我复制的命令行以下的情况：
* 下载视频的命令为：
    you-get/youtube-dl/annie + 视频网址
  例如：
    you-get https://v.youku.com/v_show/id_aBCdefGh.html
    youtube-dl https://www.youtube.com/watch?v=aBCdefGh
    annie https://www.bilibili.com/video/av12345678

* 默认下载最高清晰度。下载文件默认保存在 Download 目录。

* 如果你想选择清晰度、更改默认路径，或想了解三种工具的其他用法，请百度或参考官方
说明：
    you-get:    https://github.com/soimort/you-get/wiki/中文说明
    youtube-dl: https://github.com/ytdl-org/youtube-dl/blob/master/README.md
    annie:      https://github.com/iawia002/annie/blob/master/README.md

-----

* 高级设置
    (如需更改以下设置，请根据对应序号前往 "Deploy.bat - 高级设置" 切换相关选项)

[3/4] 下载 YouTube 等外网视频时请“为当前窗口启用全局代理”或“添加额外代理参数
”。

[3] 当前 CMD 窗口所使用的代理地址为：
      HTTP_PROXY  = http://127.0.0.1:1081
      HTTPS_PROXY = http://127.0.0.1:1081


I:\video-downloader-deploy\Download
>>>youtube-dl -f 134+140/18 -i https://www.youtube.com/channel/UCGtvPQxpuRrXeryE
WxQkAkA --external-downloader aria2c --external-downloader-args "-x 16 -k 1M"
[youtube:channel] UCGtvPQxpuRrXeryEWxQkAkA: Downloading channel page
[youtube:playlist] UUGtvPQxpuRrXeryEWxQkAkA: Downloading webpage
[download] Downloading playlist: Uploads from 温相说党史
[youtube:playlist] UUGtvPQxpuRrXeryEWxQkAkA: Downloading page #1
[youtube:playlist] UUGtvPQxpuRrXeryEWxQkAkA: Downloading page #2
[youtube:playlist] UUGtvPQxpuRrXeryEWxQkAkA: Downloading page #3
[youtube:playlist] UUGtvPQxpuRrXeryEWxQkAkA: Downloading page #4
[youtube:playlist] UUGtvPQxpuRrXeryEWxQkAkA: Downloading page #5
[youtube:playlist] playlist Uploads from 温相说党史: Downloading 508 videos
[download] Downloading video 1 of 508
[youtube] 1tfVmCJ-D0o: Downloading webpage
[download] Destination: 党史杂谈（170）—华国锋、汪东兴一举成功的奥秘所在-1tfVmC
J-D0o.f134.mp4

04/12 20:59:43 [NOTICE] Downloading 1 item(s)
[#3bb74c 0B/0B CN:1 DL:0B]
04/12 21:00:33 [NOTICE] Allocating disk space. Use --file-allocation=none to dis
able it. See --file-allocation option in man page for more details.
 *** Download Progress Summary as of Sun Apr 12 21:00:44 2020 ***
==============================================================================
[#3bb74c 624KiB/11MiB(5%) CN:5 DL:120KiB ETA:1m33s]
FILE: I:/video-downloader-deploy/Download/党史杂谈（170）—华国锋、汪东兴一举成
功的奥秘所在-1tfVmCJ-D0o.f134.mp4.part
------------------------------------------------------------------------------

[#3bb74c 9.9MiB/11MiB(86%) CN:3 DL:315KiB ETA:5s]
04/12 21:01:37 [NOTICE] Download complete: I:/video-downloader-deploy/Download/
党史杂谈（170）—华国锋、汪东兴一举成功的奥秘所在-1tfVmCJ-D0o.f134.mp4.part

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
3bb74c|OK  |   186KiB/s|I:/video-downloader-deploy/Download/党史杂谈（170）—华
国锋、汪东兴一举成功的奥秘所在-1tfVmCJ-D0o.f134.mp4.part

Status Legend:
(OK):download completed.
[aria2c] Downloaded 12130712 bytes
[download] 100% of 11.57MiB in 01:53
[download] Destination: 党史杂谈（170）—华国锋、汪东兴一举成功的奥秘所在-1tfVmC
J-D0o.f140.m4a

04/12 21:01:37 [NOTICE] Downloading 1 item(s)
[#f6e87a 0B/0B CN:1 DL:0B]
04/12 21:02:10 [NOTICE] Allocating disk space. Use --file-allocation=none to dis
able it. See --file-allocation option in man page for more details.
 *** Download Progress Summary as of Sun Apr 12 21:02:37 2020 ***
==============================================================================
[#f6e87a 26MiB/31MiB(85%) CN:5 DL:5.9MiB]
FILE: I:/video-downloader-deploy/Download/党史杂谈（170）—华国锋、汪东兴一举成
功的奥秘所在-1tfVmCJ-D0o.f140.m4a.part
------------------------------------------------------------------------------

[#f6e87a 30MiB/31MiB(97%) CN:4 DL:5.3MiB]
04/12 21:02:38 [NOTICE] Download complete: I:/video-downloader-deploy/Download/
党史杂谈（170）—华国锋、汪东兴一举成功的奥秘所在-1tfVmCJ-D0o.f140.m4a.part

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
f6e87a|OK  |   1.1MiB/s|I:/video-downloader-deploy/Download/党史杂谈（170）—华
国锋、汪东兴一举成功的奥秘所在-1tfVmCJ-D0o.f140.m4a.part

Status Legend:
(OK):download completed.
[aria2c] Downloaded 32589127 bytes
[download] 100% of 31.08MiB in 01:01
[ffmpeg] Merging formats into "党史杂谈（170）—华国锋、汪东兴一举成功的奥秘所在
-1tfVmCJ-D0o.mp4"
Deleting original file 党史杂谈（170）—华国锋、汪东兴一举成功的奥秘所在-1tfVmCJ
-D0o.f134.mp4 (pass -k to keep)
Deleting original file 党史杂谈（170）—华国锋、汪东兴一举成功的奥秘所在-1tfVmCJ
-D0o.f140.m4a (pass -k to keep)
[download] Downloading video 2 of 508
[youtube] bUq-OM5Yrls: Downloading webpage
[youtube] bUq-OM5Yrls: Downloading MPD manifest
[dashsegments] Total fragments: 79
[download] Destination: 温相说党史—继续测试一下-bUq-OM5Yrls.f134.mp4
[download]   3.8% of ~8.63MiB at 245.92KiB/s ETA 48:37

**Comment by LussacZheng** [comment]
上一条回复是你主动删除的吗？如果不是，邮箱里有评论存档，需要我接着回复吗？

**Comment by LussacZheng** [comment]
由于长时间未回复，且我最近比较忙，现暂时关闭此 Issue 。

如有需要或有人遇到相同问题，我再详细探究一下你所提到的 “youtube-dl + aria2c 下载播放列表时只有第一个视频文件通过 aria2 下载” 的问题，但不一定能给出解决方案。

此外你可以花一点时间翻阅一下 youtube-dl 的 Issues ：[search 'aria2 playlist' in Issues of ytdl-org/youtube-dl](https://github.com/ytdl-org/youtube-dl/issues?q=aria2+playlist) ，看看是不是已经有人讨论过了。
